# Generated by Django 4.1.1 on 2024-04-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_hire_date_alter_employee_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
